### PR TITLE
Setup database service

### PR DESCRIPTION
**Pull request by ceelogre**
### What does this PR do?
Add MongoDB as our database

### How to test it?
`git clone <repo>`
`git checkout origin/db-setup`
`npm install`
`npm run dev`

### CODE REVIEW

**Review by mansurissa — CHANGES_REQUESTED** [review]
Can you please use ES Modules instead of babel and uninstall it?

**Comment by ceelogre** [comment]
@mansurissa I've worked on your feedback.

**Review by 41hulk — COMMENTED** [review]
Great work, i think we can merge :)

**Review by mansurissa — APPROVED** [review]
Great

**Pull request merged**
