### PR TITLE
Added a country search app to route /country

### PR DESCRIPTION
**Pull request by KundwaBruno**
---------------------------------------------**USAGE**----------------------------------------
       1. Run the server (index.js) _It will be running locally on port 3002_
2.In your address bar Go to route `/country`
3.Enter a valid country name and hit Enter

**NB**:  You must use capitalisation while entering country names, Otherwise it wont work!

**There you go! ...You have your country Info**

### CODE REVIEW

**Review by 41hulk — COMMENTED** [review]
Great feature Bruno 👍

**Review by ceelogre — CHANGES_REQUESTED** [review]
Add a description of what your feature does and how to test it. I don't know what to do.

**Comment by ceelogre** [comment]
Capture d’écran 2020-10-08 à 15 11 18
Your package was not added to `package.json`

**Comment by ceelogre** [comment]
Uganda is a valid country name, right?
Capture d’écran 2020-10-08 à 15 47 17

**Pull request merged**
